//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add free text question.
        /// </summary>
        public static string addFreeText {
            get {
                return ResourceManager.GetString("addFreeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add multiple choices question.
        /// </summary>
        public static string addMultiple {
            get {
                return ResourceManager.GetString("addMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to answer.
        /// </summary>
        public static string answer {
            get {
                return ResourceManager.GetString("answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to answer poll.
        /// </summary>
        public static string answerPoll {
            get {
                return ResourceManager.GetString("answerPoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to answers allowed.
        /// </summary>
        public static string answersAllowed {
            get {
                return ResourceManager.GetString("answersAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poll in the air.
        /// </summary>
        public static string appTitle {
            get {
                return ResourceManager.GetString("appTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to available polls.
        /// </summary>
        public static string availablePolls {
            get {
                return ResourceManager.GetString("availablePolls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a valid choice is required!.
        /// </summary>
        public static string choiceRequired {
            get {
                return ResourceManager.GetString("choiceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to choices.
        /// </summary>
        public static string choices {
            get {
                return ResourceManager.GetString("choices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please provide a valid comment!.
        /// </summary>
        public static string commentRequired {
            get {
                return ResourceManager.GetString("commentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to created by.
        /// </summary>
        public static string createdBy {
            get {
                return ResourceManager.GetString("createdBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create free text question.
        /// </summary>
        public static string createFreeText {
            get {
                return ResourceManager.GetString("createFreeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create multiple choices question.
        /// </summary>
        public static string createMultiple {
            get {
                return ResourceManager.GetString("createMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create note.
        /// </summary>
        public static string createNote {
            get {
                return ResourceManager.GetString("createNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create poll.
        /// </summary>
        public static string createPoll {
            get {
                return ResourceManager.GetString("createPoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to created in.
        /// </summary>
        public static string creationDate {
            get {
                return ResourceManager.GetString("creationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to description.
        /// </summary>
        public static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email is required!.
        /// </summary>
        public static string emailRequired {
            get {
                return ResourceManager.GetString("emailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ouch! something went wrong!.
        /// </summary>
        public static string errorMsgTitle {
            get {
                return ResourceManager.GetString("errorMsgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expires in.
        /// </summary>
        public static string expirationDate {
            get {
                return ResourceManager.GetString("expirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expiration date is required!.
        /// </summary>
        public static string expirationDateRequired {
            get {
                return ResourceManager.GetString("expirationDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file.
        /// </summary>
        public static string file {
            get {
                return ResourceManager.GetString("file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to finish.
        /// </summary>
        public static string finish {
            get {
                return ResourceManager.GetString("finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image.
        /// </summary>
        public static string image {
            get {
                return ResourceManager.GetString("image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the image is required!.
        /// </summary>
        public static string imageRequired {
            get {
                return ResourceManager.GetString("imageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log in using your social accounts.
        /// </summary>
        public static string logInSocialAccounts {
            get {
                return ResourceManager.GetString("logInSocialAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log off.
        /// </summary>
        public static string logOff {
            get {
                return ResourceManager.GetString("logOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to multiple.
        /// </summary>
        public static string multiple {
            get {
                return ResourceManager.GetString("multiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my polls.
        /// </summary>
        public static string myPolls {
            get {
                return ResourceManager.GetString("myPolls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name is required!.
        /// </summary>
        public static string nameRequired {
            get {
                return ResourceManager.GetString("nameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to we need your location in order to proceed! Some features may get disabled!.
        /// </summary>
        public static string noLocationErrorMsg {
            get {
                return ResourceManager.GetString("noLocationErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notes.
        /// </summary>
        public static string notes {
            get {
                return ResourceManager.GetString("notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to poll.
        /// </summary>
        public static string poll {
            get {
                return ResourceManager.GetString("poll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your &apos;{0}&apos; poll were published successfully!.
        /// </summary>
        public static string pollAvailabelMsg {
            get {
                return ResourceManager.GetString("pollAvailabelMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your poll is now available!.
        /// </summary>
        public static string pollIsAvailable {
            get {
                return ResourceManager.GetString("pollIsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to publish poll.
        /// </summary>
        public static string publishPoll {
            get {
                return ResourceManager.GetString("publishPoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to questions.
        /// </summary>
        public static string questions {
            get {
                return ResourceManager.GetString("questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to range.
        /// </summary>
        public static string range {
            get {
                return ResourceManager.GetString("range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to register.
        /// </summary>
        public static string register {
            get {
                return ResourceManager.GetString("register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remember me.
        /// </summary>
        public static string rememberMe {
            get {
                return ResourceManager.GetString("rememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to results of &apos;{0}&apos; poll.
        /// </summary>
        public static string resultsOfPoll {
            get {
                return ResourceManager.GetString("resultsOfPoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to review your poll.
        /// </summary>
        public static string reviewPoll {
            get {
                return ResourceManager.GetString("reviewPoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to single.
        /// </summary>
        public static string single {
            get {
                return ResourceManager.GetString("single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to statement.
        /// </summary>
        public static string statement {
            get {
                return ResourceManager.GetString("statement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a valid statement is required!.
        /// </summary>
        public static string statementRequired {
            get {
                return ResourceManager.GetString("statementRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thank you for your participation!.
        /// </summary>
        public static string thanksParticipation {
            get {
                return ResourceManager.GetString("thanksParticipation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your answers for &apos;{0}&apos; poll were saved successfully!.
        /// </summary>
        public static string thanksParticipationMsg {
            get {
                return ResourceManager.GetString("thanksParticipationMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total answers.
        /// </summary>
        public static string totalAnswers {
            get {
                return ResourceManager.GetString("totalAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to welcome!.
        /// </summary>
        public static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
    }
}
